[server]
bind-address=":9590"
mode="debug"  # GIN mode. Either debug, release or test
boiler-mode="debug"  # Either debug or something else.

[mdb]
url="postgres://localhost/mdb?sslmode=disable&user=postgres"
