[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.1.4"

[[constraint]]
  name = "github.com/Bnei-Baruch/sqlboiler"
  branch="master"

[prune]
  go-tests = true
  unused-packages = true
