no-hooks=true
no-tests=true
no-auto-timestamps=true
no-context=true
[psql]
dbname="data_models"
host="localhost"
port=5433
user="user"
pass="password"
schema = "public"
sslmode="disable"
blacklist=["schema_migrations", "dwh_fact_download_units_by_minutes", "dwh_fact_page_enter_units_by_minutes", "dwh_content_units_measures_2018_2021"]
