no-hooks=true
no-tests=true
no-auto-timestamps=true
no-context=true
[psql]
  dbname="chronicles"
  host="localhost"
  port=5432
  user="postgres"
  pass="password"
  sslmode="disable"
  blacklist = ["schema_migrations"]
