// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DWHContentUnitsMeasures   string
	DWHDimContentUnits        string
	DWHFactPlayUnitsByMinutes string
}{
	DWHContentUnitsMeasures:   "dwh_content_units_measures",
	DWHDimContentUnits:        "dwh_dim_content_units",
	DWHFactPlayUnitsByMinutes: "dwh_fact_play_units_by_minutes",
}
